# Phase 1: fs_sample on XIAO ESP32S3 Sense (SPI microSD on Sense expansion board)
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_FS_SAMPLE_CREATE_SOME_ENTRIES=y
CONFIG_PICOLIBC_USE_MODULE=y
